#!/bin/bash
##########################################################################################
#
# Checkout source code and if user wants, check it out to a specific date.
#
# Author(s):
#    2017, Juhapekka Piiroinen <juhapekka.piiroinen@link-motion.com>
#
# Copyright (c) 2017, Link Motion Oy
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the <organization> nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##########################################################################################
set -e
REPO_URI=$1
SOURCE_ROOT=$2
REPONAME=$3
if [[ ! -z ${BRANCH} ]]; then
  BRANCH=$4
fi

if [[ ! -z ${NO_SRC_UPDATE} ]]; then
   exit 0
fi

function get_code() {
	echo "Cloning source from ${REPO_URI}/${REPONAME}.git ${BRANCH}"
	git clone ${REPO_URI}/${REPONAME}.git ${BRANCH} && cd ${REPONAME}
}

mkdir -p ${SOURCE_ROOT}
cd ${SOURCE_ROOT}
if [ -d ${REPONAME} ]; then
	CURRENT_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
	cd ${REPONAME}
	if [[ "${CURRENT_BRANCH}"=="HEAD" ]]; then
		echo "You have checked out the code at:"
		git log -1
	else
		git pull
	fi
else
	BRANCHNAME=""
	if [[ ! -z ${BRANCH} ]]; then
		BRANCHNAME=${BRANCH}
	fi

	if [[ ! -z ${PR_BRANCH} ]]; then
		BRANCH=" -b ${PR_BRANCH}"
	elif [[ ! -z ${BRANCH} ]]; then
		BRANCH=" -b ${BRANCH}"
	fi

	# checkout the source
	set +e
	get_code
	if [[ $? -eq 0 ]]; then
		set -e
		echo "Source code has been cloned."
	else
		set -e
		if [[ ! -z ${BRANCHNAME} ]]; then
			BRANCH=" -b ${BRANCHNAME}"
		else
			BRANCH=""
		fi
		get_code
	fi

	# lets checkout to a specific date if the user asked for it
	if [[ ! -z ${CHECKOUT_DATE} ]]; then
		CURRENT_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
		git checkout `git rev-list -1 --before="${CHECKOUT_DATE}" ${CURRENT_BRANCH}`
	fi
fi
